# Generated by Django 2.2.6 on 2019-10-31 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shaver_mgt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shaver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('qty', models.IntegerField()),
                ('shaver_image', models.URLField()),
            ],
            options={
                'unique_together': {('brand', 'model')},
            },
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
