# Generated by Django 2.2.6 on 2019-10-31 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shaver_mgt', '0002_auto_20191031_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shaver',
            old_name='shaver_image',
            new_name='shave_image',
        ),
    ]
